//UEwasp97.h

//************************************************************
//     作    者：                                            *
//              长沙优易软件开发有限公司(UESoft Corp.) 邝祝芳*
//     文件名称：                                            * 
//                IF97标准头文件(水和蒸汽性质计算动态连接库) *
//     完成时间：                                            *
//                2005年5月                                  *
//************************************************************ 

void P2T97(double P, double * T, int * RANGE );
void P2HL97(double P  ,double * H , int * RANGE);
void P2HG97(double P  ,double * H , int * RANGE);
void P2SL97(double P  ,double * S , int * RANGE);
void P2SG97(double P  ,double * S , int * RANGE);
void P2VL97(double P  ,double * V , int * RANGE);
void P2VG97(double P  ,double * V , int * RANGE);
void P2L97(double P   ,double * T,double * H, double *S, double *V, double *X, int * RANGE);
void P2G97(double P   ,double * T,double * H, double *S, double *V, double *X, int * RANGE);
void P2CPL97(double P ,double *CP,int * RANGE);
void P2CPG97(double P ,double *CP,int * RANGE);
void P2CVL97(double P ,double *CV,int * RANGE);
void P2CVG97(double P ,double *CV,int * RANGE);
void P2EL97(double P  ,double * E,int    * RANGE);
void P2EG97(double P  ,double * E,int    * RANGE);
void P2SSPL97(double P,double *SSP,int   * RANGE);
void P2SSPG97(double P,double *SSP,int   * RANGE);
void P2KSL97(double P ,double *KS ,int   * RANGE);
void P2KSG97(double P ,double *KS,int * RANGE);
void P2ETAL97(double P,double *ETA,int * RANGE);
void P2ETAG97(double P,double *ETA,int * RANGE);
void P2UL97(double P  ,double *U,int * RANGE);
void P2UG97(double P  ,double *U,int * RANGE);
void P2RAMDL97(double P ,double *RAMD,int * RANGE);
void P2RAMDG97(double P ,double *RAMD,int * RANGE);
void P2PRNL97(double P  ,double *PRN,int * RANGE);
void P2PRNG97(double P  ,double *PRN,int * RANGE);
void P2EPSL97(double P  ,double *EPS,int * RANGE);
void P2EPSG97(double P  ,double *EPS,int * RANGE);
void P2NL97(double P, double Lamd,double *N,int * RANGE);
void P2NG97(double P, double Lamd,double *N,int * RANGE);
void PT2H97(double P, double T,double *H,int * RANGE);
void PT2S97(double P, double T,double *S,int * RANGE);
void PT2V97(double P, double T,double *V,int * RANGE);
void PT2X97(double P, double T,double *X,int * RANGE);
void PT97(double P, double T, double * H, double *S, double *V, double *X, int * RANGE);
void PT2CP97(double P, double T,double *CP,int * RANGE);
void PT2CV97(double P, double T,double *CV,int * RANGE);
void PT2E97(double P, double T,double *E,int * RANGE);
void PT2SSP97(double P, double T,double *SSP,int * RANGE);
void PT2KS97(double P, double T,double *KS,int * RANGE);
void PT2ETA97(double P, double T,double *ETA,int * RANGE);
void PT2U97(double P, double T,double *U,int * RANGE);
void PT2RAMD97(double P, double T,double *RAMD,int * RANGE);
void PT2PRN97(double P, double T,double *PRN,int * RANGE);
void PT2EPS97(double P, double T,double *EPS,int * RANGE);
void PT2N97(double P, double T,double LAMD, double *N,int * RANGE);
void PH2T97(double P, double H,double *T,int * RANGE);
void PH2S97(double P, double H,double *S,int * RANGE);
void PH2V97(double P, double H,double *V,int * RANGE);
void PH2X97(double P, double H,double *X,int * RANGE);
void PH2SSP97(double P, double H,double *SSP,int * RANGE);
void PH97(double P  ,double *T,double H, double * S,double *V,double *X,int * RANGE);
void PS2T97(double P, double S,double *T,int * RANGE);
void PS2H97(double P, double S,double *H,int * RANGE);
void PS2V97(double P, double S,double *V,int * RANGE);
void PS2X97(double P, double S,double *X,int * RANGE);
void PS97(double P  ,double *T, double *H,double S,double *V, double *X,int * RANGE);
void PV2T97(double P, double V,double *T,int * RANGE);
void PV2H97(double P, double V,double *H,int * RANGE);
void PV2S97(double P, double V,double *S,int * RANGE);
void PV2X97(double P, double V,double *X,int * RANGE);
void PV97(double P  ,double *T, double *H, double *S,double V,double *X,int * RANGE);
void PX2T97(double P, double X,double *T,int * RANGE);
void PX2H97(double P, double X,double *H,int * RANGE);
void PX2S97(double P, double X,double *S,int * RANGE);
void PX2V97(double P, double X,double *V,int * RANGE);
void PX97(double P  ,double *T, double *H, double *S, double *V,double X,int * RANGE);
void T2P97(double T  ,double *P, int * RANGE);
void T2HL97(double T  ,double *H, int * RANGE);
void T2HG97(double T  ,double *H, int * RANGE);
void T2SL97(double T  ,double *S, int * RANGE);
void T2SG97(double T  ,double *S, int * RANGE);
void T2VL97(double T  ,double *V, int * RANGE);
void T2VG97(double T  ,double *V, int * RANGE);
void T2L97(double *P,double T  ,double *H,double *S,double *V,double *X,int * RANGE);
void T2G97(double *P,double T  ,double *H,double *S,double *V,double *X,int * RANGE);
void T2CPL97(double T  ,double *CP,int * RANGE);
void T2CPG97(double T  ,double *CP,int * RANGE);
void T2CVL97(double T  ,double *CV,int * RANGE);
void T2CVG97(double T  ,double *CV,int * RANGE);
void T2EL97(double T  ,double *E,int * RANGE);
void T2EG97(double T  ,double *E,int * RANGE);
void T2SSPL97(double T  ,double *SSP,int * RANGE);
void T2SSPG97(double T  ,double *SSP,int * RANGE);
void T2KSL97(double T  ,double *KS,int * RANGE);
void T2KSG97(double T  ,double *KS,int * RANGE);
void T2ETAL97(double T  ,double *ETA,int * RANGE);
void T2ETAG97(double T  ,double *ETA,int * RANGE);
void T2UL97(double T  ,double *U,int * RANGE);
void T2UG97(double T  ,double *U,int * RANGE);
void T2RAMDL97(double T  ,double *RAMD,int * RANGE);
void T2RAMDG97(double T  ,double *RAMD,int * RANGE);
void T2PRNL97(double T  ,double *PRN,int * RANGE);
void T2PRNG97(double T  ,double *PRN,int * RANGE);
void T2EPSL97(double T  ,double *EPS,int * RANGE);
void T2EPSG97(double T  ,double *EPS,int * RANGE);
void T2NL97(double T, double Lamd,double *N,int * RANGE);
void T2NG97(double T, double Lamd,double *N,int * RANGE);
void T2SURFT97(double T  ,double *SURFT,int * RANGE);
void TH2P97(double T, double H,double *P,int * RANGE);
void TH2PLP97(double T, double H,double *P,int * RANGE);
void TH2PHP97(double T, double H,double *P,int * RANGE);
void TH2S97(double T, double H,double *S,int * RANGE);
void TH2SLP97(double T, double H,double *S,int * RANGE);
void TH2SHP97(double T, double H,double *S,int * RANGE);
void TH2V97(double T, double H,double *V,int * RANGE);
void TH2VLP97(double T, double H,double *V,int * RANGE);
void TH2VHP97(double T, double H,double *V,int * RANGE);
void TH2X97(double T, double H,double *X,int * RANGE);
void TH2XLP97(double T, double H,double *X,int * RANGE);
void TH2XHP97(double T, double H,double *X,int * RANGE);
void TH97(double *P,double T, double H,double * S,double *V,double *X,int * RANGE);
void THLP97(double *P,double T, double H,double * S,double *V,double *X,int * RANGE);
void THHP97(double *P,double T, double H,double * S,double *V,double *X,int * RANGE);
void TS2PHP97(double T, double S,double *P,int * RANGE);
void TS2PLP97(double T, double S,double *P,int * RANGE);
void TS2P97(double T, double S,double *P,int * RANGE);
void TS2HHP97(double T, double S,double *H,int * RANGE);
void TS2HLP97(double T, double S,double *H,int * RANGE);
void TS2H97(double T, double S,double *H,int * RANGE);
void TS2VHP97(double T, double S,double *V,int * RANGE);
void TS2VLP97(double T, double S,double *V,int * RANGE);
void TS2V97(double T, double S,double *V,int * RANGE);
void TS2X97(double T, double S,double *X,int * RANGE);
void TSHP97(double *P,double T  ,double *H,double S,double *V, double *X,int * RANGE);
void TSLP97(double *P,double T  ,double *H,double S,double *V, double *X,int * RANGE);
void TS97(double *P,double T  ,double *H,double S,double *V, double *X,int * RANGE);
void TV2P97(double T, double V,double *P,int * RANGE);
void TV2H97(double T, double V,double *H,int * RANGE);
void TV2S97(double T, double V,double *S,int * RANGE);
void TV2X97(double T, double V,double *X,int * RANGE);
void TV97(double *P,double T  ,double *H,double *S ,double V , double *X,int * RANGE);
void TX2P97(double T, double X,double *P,int * RANGE);
void TX2H97(double T, double X,double *H,int * RANGE);
void TX2S97(double T, double X,double *S,int * RANGE);
void TX2V97(double T, double X,double *V,int * RANGE);
void TX97(double *P,double T  ,double *H, double *S, double *V,double X,int * RANGE);
void H2TL97(double H, double *T,int * RANGE);
void HS2P97(double H, double S,double *P,int * RANGE);
void HS2T97(double H, double S,double *T,int * RANGE);
void HS2V97(double H, double S,double *V,int * RANGE);
void HS2X97(double H, double S,double *X,int * RANGE);
void HS97(double *P, double *T,double H, double S,double *V, double *X,int * RANGE);
void HV2P97(double H, double V,double *P,int * RANGE);
void HV2T97(double H, double V,double *T,int * RANGE);
void HV2S97(double H, double V,double *S,int * RANGE);
void HV2X97(double H, double V,double *X,int * RANGE);
void HV97(double *P, double *T,double H,double *S, double V,double *X,int * RANGE);
void HX2P97(double H, double X,double *P,int * RANGE);
void HX2PLP97(double H, double X,double *P,int * RANGE);
void HX2PHP97(double H, double X,double *P,int * RANGE);
void HX2T97(double H, double X,double *T,int * RANGE);
void HX2TLP97(double H, double X,double *T,int * RANGE);
void HX2THP97(double H, double X,double *T,int * RANGE);
void HX2S97(double H, double X,double *S,int * RANGE);
void HX2SLP97(double H, double X,double *S,int * RANGE);
void HX2SHP97(double H, double X,double *S,int * RANGE);
void HX2V97(double H, double X,double *V,int * RANGE);
void HX2VLP97(double H, double X,double *V,int * RANGE);
void HX2VHP97(double H, double X,double *V,int * RANGE);
void HX97(double *P, double *T,double H,double *S, double *V,double X,int * RANGE);
void HXLP97(double *P, double *T,double H,double *S, double *V,double X,int * RANGE);
void HXHP97(double *P, double *T,double H,double *S, double *V,double X,int * RANGE);
void S2TG97(double S,double *T,int * RANGE);
void SV2P97(double S, double V,double *P,int * RANGE);
void SV2T97(double S, double V,double *T,int * RANGE);
void SV2H97(double S, double V,double *H,int * RANGE);
void SV2X97(double S, double V,double *X,int * RANGE);
void SV97(double *P, double *T, double *H,double S, double V,double *X,int * RANGE);
void SX2P97(double S, double X,double *P,int * RANGE);
void SX2PLP97(double S, double X,double *P,int * RANGE);
void SX2PMP97(double S, double X,double *P,int * RANGE);
void SX2PHP97(double S, double X,double *P,int * RANGE);
void SX2TLP97(double S, double X,double *T,int * RANGE);
void SX2TMP97(double S, double X,double *T,int * RANGE);
void SX2THP97(double S, double X,double *T,int * RANGE);
void SX2T97(double S, double X,double *T,int * RANGE);
void SX2H97(double S, double X,double *H,int * RANGE);
void SX2HLP97(double S, double X,double *H,int * RANGE);
void SX2HMP97(double S, double X,double *H,int * RANGE);
void SX2HHP97(double S, double X,double *H,int * RANGE);
void SX2V97(double S, double X,double *V,int * RANGE);
void SX2VLP97(double S, double X,double *V,int * RANGE);
void SX2VMP97(double S, double X,double *V,int * RANGE);
void SX2VHP97(double S, double X,double *V,int * RANGE);
void SX97(double *P, double *T, double *H,double S,double *V,double X,int * RANGE);
void SXLP97(double *P, double *T, double *H,double S,double *V,double X,int * RANGE);
void SXMP97(double *P, double *T, double *H,double S,double *V,double X,int * RANGE);
void SXHP97(double *P, double *T, double *H,double S,double *V,double X,int * RANGE);
void V2TG97(double V , double *T,int * RANGE);
void VX2P97(double V, double X,double *P,int * RANGE);
void VX2PLP97(double V, double X,double *P,int * RANGE);
void VX2PHP97(double V, double X,double *P,int * RANGE);
void VX2T97(double V, double X,double *T,int * RANGE);
void VX2TLP97(double V, double X,double *T,int * RANGE);
void VX2THP97(double V, double X,double *T,int * RANGE);
void VX2H97(double V, double X,double *H,int * RANGE);
void VX2HLP97(double V, double X,double *H,int * RANGE);
void VX2HHP97(double V, double X,double *H,int * RANGE);
void VX2S97(double V, double X,double *S,int * RANGE);
void VX2SLP97(double V, double X,double *S,int * RANGE);
void VX2SHP97(double V, double X,double *S,int * RANGE);
void VX97(double *P, double *T, double *H, double *S,double V, double X,int * RANGE);
void VXLP97(double *P, double *T, double *H, double *S,double V, double X,int * RANGE);
void VXHP97(double *P, double *T, double *H, double *S,double V, double X,int * RANGE);

//following 6.2 Supplementary Equation for the Metastable-Vapor Region
//rewrite by ligb on 2007.08.14 along Fortran source code by hrbrlz
double PT2VReg2MV(double P,double T);
double PT2HReg2MV(double P,double T);
double PT2EReg2MV(double P,double T);
double PT2SReg2MV(double P,double T);
double PT2CPReg2MV(double P,double T);
double PT2SSPReg2MV(double P,double T);
double PT2CVReg2MV(double P,double T);


